<?php require './php/Hero-header.php'; ?>
<?php require './php/Design.php'; ?>
<?php require './php/Cpable.php'; ?>
<?php require './php/Luxury.php'; ?>
<?php require './php/Bose-ar.php'; ?>
<?php require './php/Guarantees.php'; ?>
<?php require './php/Brand.php'; ?>
<?php require './php/Reviews.php'; ?>
<?php require './php/FAQ.php'; ?>
<?php require './php/bose-nc.php'; ?>
<?php require './php/Bose-modal.php'; ?>
<?php require './php/Footer.php'; ?>
